import type { DashboardSummary, StrategyInsight, VocRecord } from "@/types/api";

export const DEMO_VOC_RECORDS: VocRecord[] = [
  {
    voc: {
      id: "voc-001",
      source: "X/Twitter",
      title: "Dust alert",
      normalized_text: "Fine dust is terrible today. Thinking about buying an LG air purifier before the weekend.",
      product_category: "Air Purifier",
      competitor_mentions: [],
      keywords: ["fine dust", "air purifier", "purchase intent"],
      region: "Seoul",
      published_at: "2026-05-21T04:22:00Z",
      url: "https://example.com/x/002",
    },
    analysis: {
      sentiment_label: "positive",
      sentiment_score: 0.72,
      intent_label: "high",
      purchase_intent_score: 0.91,
      urgency_label: "critical",
      urgency_score: 0.88,
      complaint_type: null,
      topic_label: "Purchase Intent",
      confidence: 0.93,
    },
    lead_score: {
      id: "lead-001",
      lead_score: 91,
      priority: "high",
      score_reason: {
        purchase_intent: 32,
        urgency: 13,
        competitor_comparison: 0,
        product_category: 9,
        external_context: 10,
        sentiment_adjustment: 9,
        engagement: 8,
      },
    },
    insight: {
      id: "ins-001",
      voc_id: "voc-001",
      lead_score_id: "lead-001",
      title: "Air Purifier Surge — Fine Dust Spike Driving Immediate Purchase",
      summary: "Seoul fine dust alert triggered high-urgency purchase intent for LG air purifiers. Weekend purchase window is open.",
      recommended_action: "Deploy targeted ad campaign to Seoul residents with same-day delivery offer for air purifiers. Offer filter subscription bundle discount for first-time buyers.",
      reasoning: "PM2.5 index exceeded 80 µg/m³ in Seoul metro area. X/Twitter engagement spiked 3× within 6 hours. Purchase intent score of 0.91 with critical urgency indicates a closing purchase window.",
      priority: "high",
      target_segment: "Seoul apartment residents aged 25-45 with children",
      confidence: 0.93,
      created_at: "2026-05-21T05:00:00Z",
    },
    context: {
      context_type: "air_quality",
      region: "Seoul",
      match_reason: "PM2.5 index spike on publish date",
      match_score: 0.95,
    },
  },
  {
    voc: {
      id: "voc-002",
      source: "Naver Blog",
      title: "신혼가전 구독 고민",
      normalized_text: "이사 준비하면서 냉장고와 세탁기를 한 번에 살지 구독형 가전 케어로 시작할지 고민 중입니다. 초기 비용 할인 있으면 바로 상담받고 싶어요.",
      product_category: "Subscription Care",
      competitor_mentions: [],
      keywords: ["신혼", "구독", "냉장고", "세탁기", "초기비용 할인", "이사"],
      region: "Seoul",
      published_at: "2026-05-21T00:30:00Z",
      url: "https://example.com/naver/001",
    },
    analysis: {
      sentiment_label: "neutral",
      sentiment_score: 0.55,
      intent_label: "high",
      purchase_intent_score: 0.89,
      urgency_label: "critical",
      urgency_score: 0.85,
      complaint_type: null,
      topic_label: "Subscription Care",
      confidence: 0.91,
    },
    lead_score: {
      id: "lead-002",
      lead_score: 88,
      priority: "high",
      score_reason: {
        purchase_intent: 31,
        urgency: 13,
        competitor_comparison: 0,
        product_category: 10,
        external_context: 8,
        sentiment_adjustment: 6,
        engagement: 9,
      },
    },
    insight: {
      id: "ins-002",
      voc_id: "voc-002",
      lead_score_id: "lead-002",
      title: "신혼이사 구독 케어 패키지 상담 전환 기회",
      summary: "이사를 앞둔 신혼 고객이 구독 케어 패키지에 강한 관심을 보이며 초기 비용 할인 시 즉시 상담 의향을 밝혔습니다.",
      recommended_action: "신혼 패키지 구독 케어 무료 상담 예약 링크를 네이버 채널로 즉시 발송. 냉장고+세탁기 2종 번들 첫 달 50% 할인 오퍼 제시.",
      reasoning: "신혼·이사 키워드 + 구독형 + 초기비용 언급은 구매 결정 직전 단계의 전형적인 시그널. 입주물량 데이터와 맞물려 5월 이사 시즌 특수 확인됨.",
      priority: "high",
      target_segment: "수도권 이사 준비 신혼부부 (25-35세)",
      confidence: 0.91,
      created_at: "2026-05-21T01:00:00Z",
    },
    context: {
      context_type: "housing",
      region: "Seoul",
      match_reason: "5월 입주물량 증가 시즌과 매칭",
      match_score: 0.88,
    },
  },
  {
    voc: {
      id: "voc-003",
      source: "X/Twitter",
      title: "Styler purchase intent",
      normalized_text: "Trying LG Styler at the store convinced me. I want to buy one if delivery and setup are available next week.",
      product_category: "LG Styler",
      competitor_mentions: [],
      keywords: ["Styler", "purchase", "delivery", "setup", "next week"],
      region: "Seoul",
      published_at: "2026-05-20T06:35:00Z",
      url: "https://example.com/x/004",
    },
    analysis: {
      sentiment_label: "positive",
      sentiment_score: 0.88,
      intent_label: "high",
      purchase_intent_score: 0.94,
      urgency_label: "critical",
      urgency_score: 0.82,
      complaint_type: null,
      topic_label: "Purchase Intent",
      confidence: 0.95,
    },
    lead_score: {
      id: "lead-003",
      lead_score: 85,
      priority: "high",
      score_reason: {
        purchase_intent: 33,
        urgency: 12,
        competitor_comparison: 0,
        product_category: 8,
        external_context: 6,
        sentiment_adjustment: 10,
        engagement: 6,
      },
    },
    insight: {
      id: "ins-003",
      voc_id: "voc-003",
      lead_score_id: "lead-003",
      title: "In-Store Demo Converted — Styler Delivery Opportunity",
      summary: "Customer was convinced after in-store Styler demo. Delivery logistics is the only remaining barrier to close the sale.",
      recommended_action: "Contact customer within 2 hours to confirm next-week delivery slot. Offer free setup and 3-month care subscription as closing incentive.",
      reasoning: "In-store trial with immediate purchase intent and specific delivery timing request is the highest-quality lead signal. Immediate follow-up has >85% conversion probability based on engagement data.",
      priority: "high",
      target_segment: "Urban professionals who visited LG flagship stores",
      confidence: 0.95,
      created_at: "2026-05-20T07:00:00Z",
    },
    context: {
      context_type: "weather",
      region: "Seoul",
      match_reason: "Spring humidity driving interest in garment care",
      match_score: 0.72,
    },
  },
  {
    voc: {
      id: "voc-004",
      source: "Reddit",
      title: "Air purifier for kids",
      normalized_text: "With bad fine dust this week, I am looking to buy an LG air purifier for a room with kids. Filter subscription sounds useful if the price is reasonable.",
      product_category: "Air Purifier",
      competitor_mentions: [],
      keywords: ["fine dust", "kids", "air purifier", "filter subscription"],
      region: "Global",
      published_at: "2026-05-18T11:12:00Z",
      url: "https://example.com/reddit/003",
    },
    analysis: {
      sentiment_label: "positive",
      sentiment_score: 0.65,
      intent_label: "high",
      purchase_intent_score: 0.82,
      urgency_label: "medium",
      urgency_score: 0.68,
      complaint_type: null,
      topic_label: "Purchase Intent",
      confidence: 0.87,
    },
    lead_score: {
      id: "lead-004",
      lead_score: 79,
      priority: "medium",
      score_reason: {
        purchase_intent: 29,
        urgency: 10,
        competitor_comparison: 0,
        product_category: 9,
        external_context: 9,
        sentiment_adjustment: 7,
        engagement: 7,
      },
    },
    insight: {
      id: "ins-004",
      voc_id: "voc-004",
      lead_score_id: "lead-004",
      title: "Parent-Driven Air Purifier Demand — Filter Subscription Upsell",
      summary: "Parent with child safety concern is open to LG air purifier with filter subscription if price is competitive.",
      recommended_action: "Present LG PuriCare bundle with 6-month filter subscription at family pricing. Highlight child-safe filter materials and auto PM2.5 detection.",
      reasoning: "Child safety + fine dust event + subscription openness = high-value long-term customer. Reddit engagement of 88 indicates strong community resonance for this concern.",
      priority: "medium",
      target_segment: "Parents with children aged 1-10 in urban areas",
      confidence: 0.87,
      created_at: "2026-05-18T12:00:00Z",
    },
    context: {
      context_type: "air_quality",
      region: "Seoul",
      match_reason: "Fine dust index elevated on publish date",
      match_score: 0.89,
    },
  },
  {
    voc: {
      id: "voc-005",
      source: "Reddit",
      title: "LG vs Samsung washer",
      normalized_text: "I am comparing LG washer with Samsung. LG has better reviews for quiet operation, but I want to know if ThinQ app connectivity is reliable.",
      product_category: "Washer",
      competitor_mentions: ["Samsung"],
      keywords: ["LG vs Samsung", "washer comparison", "ThinQ connectivity", "quiet operation"],
      region: "Global",
      published_at: "2026-05-20T03:22:00Z",
      url: "https://example.com/reddit/001",
    },
    analysis: {
      sentiment_label: "neutral",
      sentiment_score: 0.51,
      intent_label: "high",
      purchase_intent_score: 0.78,
      urgency_label: "medium",
      urgency_score: 0.62,
      complaint_type: null,
      topic_label: "Competitor Comparison",
      confidence: 0.84,
    },
    lead_score: {
      id: "lead-005",
      lead_score: 74,
      priority: "medium",
      score_reason: {
        purchase_intent: 27,
        urgency: 9,
        competitor_comparison: 8,
        product_category: 8,
        external_context: 5,
        sentiment_adjustment: 5,
        engagement: 10,
      },
    },
    insight: {
      id: "ins-005",
      voc_id: "voc-005",
      lead_score_id: "lead-005",
      title: "LG vs Samsung Decision Gate — ThinQ Reliability Is the Tiebreaker",
      summary: "Customer is in final comparison stage. LG leads on hardware but ThinQ connectivity reliability is the deciding factor.",
      recommended_action: "Share ThinQ reliability improvement case study and offer 30-day free smart home trial. Connect customer with LG ThinQ community forum.",
      reasoning: "Competitor comparison with specific feature inquiry (ThinQ app) at high engagement (46 upvotes) is a decision-gate signal. Converting here prevents Samsung win.",
      priority: "medium",
      target_segment: "Tech-savvy urban consumers comparing premium washer brands",
      confidence: 0.84,
      created_at: "2026-05-20T04:00:00Z",
    },
    context: {
      context_type: "housing",
      region: "Seoul",
      match_reason: "Spring moving season correlated with washer purchase timing",
      match_score: 0.61,
    },
  },
  {
    voc: {
      id: "voc-006",
      source: "Danawa",
      title: "Energy saving mode is useful",
      normalized_text: "The new washer energy saving mode helped reduce electricity usage. I am considering subscription care if it includes regular maintenance.",
      product_category: "Washer",
      competitor_mentions: [],
      keywords: ["energy saving", "electricity usage", "subscription care", "maintenance"],
      region: "Busan",
      published_at: "2026-05-18T22:05:00Z",
      url: "https://example.com/danawa/003",
    },
    analysis: {
      sentiment_label: "positive",
      sentiment_score: 0.81,
      intent_label: "medium",
      purchase_intent_score: 0.67,
      urgency_label: "low",
      urgency_score: 0.41,
      complaint_type: null,
      topic_label: "Subscription Care",
      confidence: 0.79,
    },
    lead_score: {
      id: "lead-006",
      lead_score: 66,
      priority: "medium",
      score_reason: {
        purchase_intent: 23,
        urgency: 6,
        competitor_comparison: 0,
        product_category: 8,
        external_context: 7,
        sentiment_adjustment: 9,
        engagement: 7,
      },
    },
    insight: {
      id: "ins-006",
      voc_id: "voc-006",
      lead_score_id: "lead-006",
      title: "Energy Efficiency Satisfaction — Subscription Upsell Window",
      summary: "Current LG washer owner is satisfied with energy savings and open to subscription care upgrade.",
      recommended_action: "Send personalized subscription care onboarding offer highlighting maintenance + filter schedule. Position as natural complement to energy efficiency satisfaction.",
      reasoning: "Existing satisfied customer expressing subscription interest is a high-conversion upsell target. Energy bill savings + subscription care creates a strong value proposition story.",
      priority: "medium",
      target_segment: "Existing LG washer owners in Busan interested in energy efficiency",
      confidence: 0.79,
      created_at: "2026-05-18T23:00:00Z",
    },
    context: {
      context_type: "energy",
      region: "Busan",
      match_reason: "Summer electricity rate hike alert period",
      match_score: 0.74,
    },
  },
  {
    voc: {
      id: "voc-007",
      source: "Danawa",
      title: "Subscription care price concern",
      normalized_text: "LG Styler subscription care is convenient, but the renewal price feels too expensive compared with Samsung care plans. I might switch if there is no discount.",
      product_category: "LG Styler",
      competitor_mentions: ["Samsung"],
      keywords: ["subscription price", "renewal", "Samsung care", "discount", "switch"],
      region: "Seoul",
      published_at: "2026-05-20T09:10:00Z",
      url: "https://example.com/danawa/001",
    },
    analysis: {
      sentiment_label: "negative",
      sentiment_score: 0.28,
      intent_label: "medium",
      purchase_intent_score: 0.55,
      urgency_label: "medium",
      urgency_score: 0.61,
      complaint_type: "price_concern",
      topic_label: "Subscription Pricing",
      confidence: 0.82,
    },
    lead_score: {
      id: "lead-007",
      lead_score: 57,
      priority: "medium",
      score_reason: {
        purchase_intent: 19,
        urgency: 9,
        competitor_comparison: 8,
        product_category: 7,
        external_context: 4,
        sentiment_adjustment: 3,
        engagement: 7,
      },
    },
    insight: {
      id: "ins-007",
      voc_id: "voc-007",
      lead_score_id: "lead-007",
      title: "Churn Risk — Subscription Renewal Price vs Samsung",
      summary: "Existing LG Styler subscriber is comparing renewal pricing with Samsung and signaling churn risk without a discount offer.",
      recommended_action: "Issue retention discount coupon (15-20% off renewal) via app push notification. Present LG-exclusive benefits Samsung cannot match (Styler-specific filter care).",
      reasoning: "Churn risk with competitor mention requires immediate intervention. Acquisition cost of replacement is 4-5× higher than retention discount cost.",
      priority: "medium",
      target_segment: "Existing LG Styler subscription care customers at renewal stage",
      confidence: 0.82,
      created_at: "2026-05-20T10:00:00Z",
    },
    context: {
      context_type: "energy",
      region: "Seoul",
      match_reason: "Subscription renewal pricing correlates with energy cost awareness",
      match_score: 0.58,
    },
  },
  {
    voc: {
      id: "voc-008",
      source: "YouTube",
      title: "Care plan question",
      normalized_text: "Does subscription care include regular cleaning and filter replacement? If yes, I want a quote for air purifier and air conditioner together.",
      product_category: "Subscription Care",
      competitor_mentions: [],
      keywords: ["subscription care", "filter replacement", "air purifier", "air conditioner", "bundle quote"],
      region: "Global",
      published_at: "2026-05-17T12:00:00Z",
      url: "https://example.com/youtube/004",
    },
    analysis: {
      sentiment_label: "neutral",
      sentiment_score: 0.58,
      intent_label: "high",
      purchase_intent_score: 0.85,
      urgency_label: "medium",
      urgency_score: 0.65,
      complaint_type: null,
      topic_label: "Subscription Care",
      confidence: 0.88,
    },
    lead_score: {
      id: "lead-008",
      lead_score: 72,
      priority: "medium",
      score_reason: {
        purchase_intent: 30,
        urgency: 10,
        competitor_comparison: 0,
        product_category: 10,
        external_context: 7,
        sentiment_adjustment: 6,
        engagement: 9,
      },
    },
    insight: {
      id: "ins-008",
      voc_id: "voc-008",
      lead_score_id: "lead-008",
      title: "Multi-Product Bundle Inquiry — High-Value Subscription Opportunity",
      summary: "Customer is actively seeking a combined air purifier + air conditioner subscription care bundle, indicating high-value multi-product purchase intent.",
      recommended_action: "Send bundled subscription care quote for air purifier + AC within 24h. Offer combo discount and single monthly bill convenience as key selling points.",
      reasoning: "Multi-product bundle inquiries represent 2.5× average revenue vs single-product subscriptions. YouTube comment visibility (67 engagements) amplifies brand awareness opportunity.",
      priority: "medium",
      target_segment: "Multi-product household owners considering full home subscription",
      confidence: 0.88,
      created_at: "2026-05-17T13:00:00Z",
    },
    context: {
      context_type: "air_quality",
      region: "Seoul",
      match_reason: "High fine dust season increases multi-product air care demand",
      match_score: 0.77,
    },
  },
  {
    voc: {
      id: "voc-009",
      source: "Reddit",
      title: "ThinQ app keeps disconnecting",
      normalized_text: "My LG air conditioner disconnects from the ThinQ app every few days. The hardware is fine, but the app connection problem is annoying.",
      product_category: "Air Conditioner",
      competitor_mentions: [],
      keywords: ["ThinQ app", "disconnect", "connectivity", "air conditioner"],
      region: "Global",
      published_at: "2026-05-19T05:30:00Z",
      url: "https://example.com/reddit/002",
    },
    analysis: {
      sentiment_label: "negative",
      sentiment_score: 0.22,
      intent_label: "low",
      purchase_intent_score: 0.21,
      urgency_label: "medium",
      urgency_score: 0.58,
      complaint_type: "app_issue",
      topic_label: "App Connectivity",
      confidence: 0.86,
    },
    lead_score: {
      id: "lead-009",
      lead_score: 34,
      priority: "low",
      score_reason: {
        purchase_intent: 7,
        urgency: 9,
        competitor_comparison: 0,
        product_category: 6,
        external_context: 4,
        sentiment_adjustment: 2,
        engagement: 6,
      },
    },
    insight: {
      id: "ins-009",
      voc_id: "voc-009",
      lead_score_id: "lead-009",
      title: "ThinQ Connectivity Complaint — CX Escalation Required",
      summary: "Recurring ThinQ app disconnection issue is damaging customer experience with a satisfied hardware user. Risk of negative word-of-mouth at 71 upvote exposure.",
      recommended_action: "Route to CX technical team for ThinQ firmware investigation. Proactively post ThinQ update notice in Reddit thread. Monitor for community amplification.",
      reasoning: "High engagement (71 upvotes) on a complaint thread means each unresolved comment risks negative word-of-mouth. CX resolution prevents further NPS damage.",
      priority: "low",
      target_segment: "Existing LG AC owners with ThinQ connectivity issues",
      confidence: 0.86,
      created_at: "2026-05-19T06:00:00Z",
    },
    context: {
      context_type: "weather",
      region: "Seoul",
      match_reason: "Pre-summer season air conditioner usage surge",
      match_score: 0.55,
    },
  },
  {
    voc: {
      id: "voc-010",
      source: "Danawa",
      title: "Refrigerator noise issue",
      normalized_text: "The refrigerator cooling is strong, but the compressor noise is louder than expected. Need service check before recommending it.",
      product_category: "Refrigerator",
      competitor_mentions: [],
      keywords: ["refrigerator", "compressor noise", "service check"],
      region: "Daegu",
      published_at: "2026-05-17T17:20:00Z",
      url: "https://example.com/danawa/004",
    },
    analysis: {
      sentiment_label: "negative",
      sentiment_score: 0.31,
      intent_label: "low",
      purchase_intent_score: 0.18,
      urgency_label: "medium",
      urgency_score: 0.54,
      complaint_type: "product_defect",
      topic_label: "Product Quality",
      confidence: 0.81,
    },
    lead_score: {
      id: "lead-010",
      lead_score: 29,
      priority: "low",
      score_reason: {
        purchase_intent: 6,
        urgency: 8,
        competitor_comparison: 0,
        product_category: 5,
        external_context: 3,
        sentiment_adjustment: 2,
        engagement: 5,
      },
    },
    insight: {
      id: "ins-010",
      voc_id: "voc-010",
      lead_score_id: "lead-010",
      title: "Refrigerator Noise Defect — Service Dispatch Priority",
      summary: "Customer reports compressor noise issue blocking word-of-mouth recommendation. Service resolution has direct impact on secondary purchase influence.",
      recommended_action: "Schedule proactive service engineer visit within 3 business days. After resolution, send satisfaction survey and referral incentive to recover recommendation potential.",
      reasoning: "Customer explicitly states they would recommend after service fix — recoverable churn. Quick service dispatch converts a complaint into a referral opportunity.",
      priority: "low",
      target_segment: "Recent LG refrigerator buyers in Daegu with hardware complaints",
      confidence: 0.81,
      created_at: "2026-05-17T18:00:00Z",
    },
    context: {
      context_type: "weather",
      region: "Daegu",
      match_reason: "Rising temperatures increase refrigerator usage and noise sensitivity",
      match_score: 0.62,
    },
  },
];

export const DEMO_DASHBOARD_SUMMARY: DashboardSummary = {
  total_voc_collected: 20,
  high_priority_leads: 3,
  negative_voc_rate: 30,
  purchase_intent_detected: 7,
  average_lead_score: 68,
  sentiment_breakdown: { positive: 6, neutral: 7, negative: 7 },
  urgency_breakdown: { critical: 3, medium: 5, low: 2 },
  platform_distribution: {
    Danawa: 4,
    Reddit: 4,
    "Naver Blog": 4,
    YouTube: 4,
    "X/Twitter": 4,
  },
  top_keywords: [
    "subscription care",
    "fine dust",
    "ThinQ connectivity",
    "purchase intent",
    "Samsung comparison",
    "energy saving",
    "filter replacement",
    "air purifier",
    "신혼 이사",
  ],
  topic_clusters: [
    { topic: "Purchase Intent", count: 5, status: "rising" },
    { topic: "Subscription Care", count: 4, status: "stable" },
    { topic: "App Connectivity", count: 3, status: "critical" },
    { topic: "Competitor Comparison", count: 2, status: "rising" },
    { topic: "Product Quality", count: 2, status: "stable" },
    { topic: "Subscription Pricing", count: 2, status: "declining" },
  ],
  high_priority_preview: DEMO_VOC_RECORDS.filter((r) => r.lead_score.priority === "high"),
  featured_insight: DEMO_VOC_RECORDS[0].insight,
};

export const DEMO_INSIGHTS: StrategyInsight[] = DEMO_VOC_RECORDS.map((r) => r.insight);
